### ISSUE TITLE
Bug when decrementing item quantity

### ISSUE THREAD

**Issue by JohnHillegass** [jasierragarcia/bitshop#3]
When decrementing item quantity I am able to add a negative number. We should rework this so nothing less than zero is allowed.

**Comment by jasierragarcia** [comment]
Thanks for finding the bug! Will push small update to fix this bug tonight

**Comment by jasierragarcia** [comment]
The bug has been fixed! I think the function could be improved though, so I'm going to keep iterating it

**Comment by JohnHillegass** [comment]
Sounds good to me sir ! Talk with you soon.
